default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] || "dummy_dev" %>
  host:     <%= ENV["DATABASE_HOST"] || "localhost" %>
  username: <%= ENV["DATABASE_USER"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "" %>

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] || "dummy_test" %>
  host:     <%= ENV["DATABASE_HOST"] || "localhost" %>
  username: <%= ENV["DATABASE_USER"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "" %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", nil) %>
